version: '3'
services:
  ggnb-proxy:
    # build: ./nginx
    image: nginx:1.19
    depends_on: 
      - ggnb-frontend
      - ggnb-backend
    volumes: 
      - ./nginx/nginx_dev.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80
  ggnb-frontend:
    container_name: ggnb-frontend
    image: lihongming1/ggnb-frontend:2.0.7
    build: ./frontend
    working_dir: /var/opt
    depends_on:
      - ggnb-backend
    expose: 
      - "3000"
    command: npm run start
    env_file: ./frontend/.env.local
  ggnb-backend:
    container_name: ggnb-backend
    image: lihongming1/ggnb-backend:2.0.7
    build: ./backend
    working_dir: /var/opt
    depends_on:
      - ggnb-database
    ports: 
      - 5000:5000
    expose: 
      - "5001"
    command: npm run start
    env_file: ./backend/.env
  ggnb-database:
    container_name: ggnb-database
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ggnb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    expose:
      - "5432"